spring:
  application:
    name: snaplink-api

  datasource:
    url: jdbc:postgresql://localhost:5432/snaplink_db
    username: snaplink_user
    password: snaplink_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Apenas para desenvolvimento rápido. Em produção, usaríamos Flyway/Liquibase.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

# Expondo o Actuator para ferramentas de monitoramento
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springdoc: DEBUG